package pkg

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ShrkoModName is the manifest that `shirocc mod` writes.
const ShrkoModName = "shiroko.shrkomod"

// ModFile is a parsed shiroko.shrkomod. The file is a flat list of
// import paths, one per line, with `#` comments allowed.
type ModFile struct {
	Path    string
	Imports []string
}

// LoadModFile reads dir/shiroko.shrkomod. Missing file is not an
// error — it just yields an empty ModFile.
func LoadModFile(dir string) (*ModFile, error) {
	path := filepath.Join(dir, ShrkoModName)
	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return &ModFile{Path: path}, nil
	}
	if err != nil {
		return nil, err
	}
	defer f.Close()

	mf := &ModFile{Path: path}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		mf.Imports = append(mf.Imports, line)
	}
	return mf, sc.Err()
}

// Add appends name if not already present. Returns true when the file
// content changed.
func (m *ModFile) Add(name string) bool {
	for _, i := range m.Imports {
		if i == name {
			return false
		}
	}
	m.Imports = append(m.Imports, name)
	return true
}

// Save writes the file back, sorted.
func (m *ModFile) Save() error {
	sort.Strings(m.Imports)
	var b strings.Builder
	b.WriteString("# shiroko.shrkomod — generated by `shirocc mod`\n")
	b.WriteString("# one import path per line: <package>/<module>\n\n")
	for _, i := range m.Imports {
		b.WriteString(i)
		b.WriteByte('\n')
	}
	return os.WriteFile(m.Path, []byte(b.String()), 0o644)
}

// ValidateImportPath accepts `<name>` or `<package>/<module>`.
// Rejects empty, leading/trailing slash, or more than one slash.
func ValidateImportPath(p string) error {
	if p == "" {
		return fmt.Errorf("import path is empty")
	}
	i := strings.IndexByte(p, '/')
	if i < 0 {
		return nil // bare name
	}
	if i == 0 || i == len(p)-1 || strings.IndexByte(p[i+1:], '/') >= 0 {
		return fmt.Errorf("import path %q must be <name> or <package>/<module>", p)
	}
	return nil
}
